# Generated by Django 5.0.7 on 2025-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0006_alter_auditlog_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="bakery_audi_table_b625f3_idx",
            old_name="bakery_audit_table_2a8f7d_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="bakery_audi_action_2fe2fa_idx",
            old_name="bakery_audit_action_2098a0_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="bakery_audi_created_5b6516_idx",
            old_name="bakery_audit_created_0e6714_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
