# Generated by Django 5.0.7 on 2025-10-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0008_employee_attendance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_present",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gross_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_entries",
                        to="bakery.employee",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="bakery.payrollperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "employee_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollentry",
            constraint=models.UniqueConstraint(
                fields=("period", "employee"), name="uniq_payroll_period_employee"
            ),
        ),
    ]
