# Generated by Django 5.0.7 on 2025-10-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0010_importpreset_importjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="CogsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[("FIFO", "FIFO"), ("FEFO", "FEFO")],
                        default="FIFO",
                        max_length=4,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bakery.outlet"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bakery.product"
                    ),
                ),
                (
                    "sale_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cogs_entry",
                        to="bakery.saleitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at", "sale_item_id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.CharField(max_length=64)),
                ("received_at", models.DateField()),
                ("qty_in", models.FloatField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qty_remaining", models.FloatField()),
                ("expiry", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_batches",
                        to="bakery.outlet",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_batches",
                        to="bakery.product",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry", "received_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "outlet", "expiry"],
                        name="bakery_purc_product_9e811a_idx",
                    ),
                    models.Index(
                        fields=["outlet", "expiry"],
                        name="bakery_purc_outlet__bcfc4d_idx",
                    ),
                ],
            },
        ),
    ]
