# Generated by Django 5.0.7 on 2025-10-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0012_perf_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sale",
            name="sale_billed_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="sale_outlet_billed_idx",
        ),
        migrations.RemoveIndex(
            model_name="saleitem",
            name="saleitem_sale_idx",
        ),
        migrations.RemoveIndex(
            model_name="saleitem",
            name="saleitem_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockledger",
            name="stockledger_batch_idx",
        ),
    ]
