# Generated by Django 5.0.7 on 2025-10-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0013_remove_sale_sale_billed_at_idx_and_more"),
        ("bakery", "0013_uploadtask"),
    ]

    operations = []
