# Generated by Django 5.0.7 on 2025-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0014_merge_20251008_0058"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="qty_per_unit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="wastage_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("product",), name="uniq_recipe_product_cogs"
            ),
        ),
    ]
